# Project Details

name: "dbt_modern_analytics"
version: "1.0.0"
profile: "dbt-modern-analytics"

# File Path Configuration

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`

clean-targets:
  - "target"
  - "dbt_packages"

# Variables

vars:
  dbt_audit_database: "{{ env_var('DBT_MA_ENV_DB') }}"
  dbt_audit_schema: dbt_audit
  dbt_audit_table: dbt_run

# Run Hooks

on-run-start:
  - "{{ dbt_audit_start_exec(invocation_id, 'Full Execution', 'Full Execution') }}"

on-run-end:
  - "{{ dbt_audit_finish_exec(invocation_id, 'Full Execution') }}"

# Model Configuration

models:
  dbt_modern_analytics:
    +materialized: view

    sources:
      +database: "{{ env_var('DBT_MA_ENV_DB') }}"
      +schema: sources
      +tags: ["sources"]
      +materialized: view

    staging:
      +database: "{{ env_var('DBT_MA_ENV_DB') }}"
      +schema: staging
      +tags: ["staging"]
      +materialized: table

    marts:
      +database: "{{ env_var('DBT_MA_ENV_DB') }}"
      +schema: sales_mart
      +tags: ["sales_mart"]
      +materialized: table
