# Project Details

name: "dbt_modern_analytics"
version: "1.0.0"
profile: "dbt-modern-analytics"

# File Path Configuration

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`

clean-targets:
  - "target"
  - "dbt_packages"

# Model Configuration

models:
  dbt_modern_analytics:
    +materialized: view

    sources:
      +database: "{{ env_var('DBT_MA_STG') }}"
      +schema: sources
      +tags: ["sources"]
      +materialized: view

    staging:
      +database: "{{ env_var('DBT_MA_STG') }}"
      +schema: staging
      +tags: ["staging"]
      +materialized: table

    marts:
      +database: "{{ env_var('DBT_MA_STG') }}"
      +schema: sales_mart
      +tags: ["sales_mart"]
      +materialized: table
