# Project Details

name: "dbt_modern_analytics"
version: "1.0.0"
profile: "dbt-modern-analytics"

# File Path Configuration

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`

clean-targets:
  - "target"
  - "dbt_packages"

# Variables

vars:
  dbt_audit_database: "{{ target.database }}"
  dbt_audit_schema: dbt_audit
  dbt_audit_table: dbt_run

# Run Hooks

on-run-start:
  - "{{ dbt_audit_started_exec() }}"

on-run-end:
  - "{{ dbt_audit_finished_exec() }}"

# Model Configuration

models:
  dbt_modern_analytics:
    +database: "{{ target.database }}"
    +materialized: view
    +pre-hook:
      - "{{ dbt_audit_started_exec() }}"
    +post-hook:
      - "{{ dbt_audit_finished_exec() }}"

    sources:
      +schema: sources
      +tags: ["sources"]
      +materialized: view

    staging:
      +schema: staging
      +tags: ["staging"]
      +materialized: table

    marts:
      +schema: sales_mart
      +tags: ["sales_mart"]
      +materialized: table

    wip:
      +tags: ["wip"]

snapshots:
  dbt_modern_analytics:
    +target_schema: dbt_snapshots
    +pre-hook:
      - "{{ dbt_audit_started_exec() }}"
    +post-hook:
      - "{{ dbt_audit_finished_exec() }}"
