version: 2

models:
  - name: sales_source
    description: "Raw sales data sourced from a Snowflake stage"
    columns:
      - name: order_date
        description: "The date of the order."
        tests:
          - not_null

      - name: product_id
        description: "The identifier for the product."
        tests:
          - not_null

      - name: campaign_id
        description: "The identifier for the campaign."
        tests:
          - not_null

      - name: customer_id
        description: "The identifier for the customer."
        tests:
          - not_null

      - name: manufacturer_id
        description: "The identifier for the manufacturer."
        tests:
          - not_null

      - name: zip_code
        description: "The ZIP code of the customer's location."

      - name: city
        description: "The city of the customer's location."

      - name: state
        description: "The state of the customer's location."

      - name: district
        description: "The district of the customer's location."

      - name: region
        description: "The region of the customer's location."

      - name: country
        description: "The country of the customer's location."

      - name: product
        description: "The name of the product."

      - name: category
        description: "The category of the product."

      - name: segment
        description: "The segment of the product."

      - name: unit_cost
        description: "The cost per unit of the product."
        tests:
          - not_null

      - name: unit_price
        description: "The selling price per unit of the product."
        tests:
          - not_null

      - name: email_name
        description: "Concatenates the Email and Name of the customer into a string."

      - name: manufacturer
        description: "The name of the manufacturer."

      - name: units
        description: "The number of units sold."
        tests:
          - not_null

      - name: load_date
        description: "The date when the data was loaded into the AWS bucket."
        tests:
          - not_null
