version: 2

models:
  - name: sales_staging
    description: >
      This model represents the final cleaned and enriched sales data, combining information from the `deduped` table
      with additional state and country details.
    columns:
      - name: sales_id
        description: "The unique identifier for the sales record."
        data_tests:
          - not_null
          - unique

      - name: order_date
        description: "The date of the order."
        data_tests:
          - not_null

      - name: product_id
        description: "The identifier for the product."
        data_tests:
          - not_null

      - name: campaign_id
        description: "The identifier for the campaign."
        data_tests:
          - not_null

      - name: customer_id
        description: "The identifier for the customer."
        data_tests:
          - not_null

      - name: manufacturer_id
        description: "The identifier for the manufacturer."
        data_tests:
          - not_null

      - name: zip_code
        description: "The ZIP code of the customer's location."
        data_tests:
          - not_null

      - name: city
        description: "The city of the customer's location."

      - name: state
        description: "The state of the customer's location."

      - name: district
        description: "The district of the customer's location."

      - name: region
        description: "The region where the order was placed."

      - name: country
        description: "The country of the customer's location."

      - name: product
        description: "The name of the product."

      - name: category
        description: "The category of the product."

      - name: segment
        description: "The segment of the product."

      - name: unit_cost
        description: "The cost per unit of the product."
        data_tests:
          - not_null

      - name: unit_price
        description: "The selling price per unit of the product."
        data_tests:
          - not_null

      - name: email
        description: "The email address of the customer."

      - name: first_name
        description: "The first name of the customer."

      - name: last_name
        description: "The last name of the customer."

      - name: manufacturer
        description: "The name of the manufacturer."

      - name: units
        description: "The number of units sold."
        data_tests:
          - not_null

      - name: load_date
        description: "The date when the data was loaded into the staging environment."
        data_tests:
          - not_null

      - name: updated_ts
        description: "The timestamp when the record was last updated."
        data_tests:
          - not_null
